"""Initial migration

Revision ID: 164b31cdf665
Revises: 
Create Date: 2025-05-24 19:24:50.224979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '164b31cdf665'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_priority', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_component_categories_id'), 'component_categories', ['id'], unique=False)
    op.create_index(op.f('ix_component_categories_name'), 'component_categories', ['name'], unique=False)
    op.create_table('configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_uuid', sa.String(length=36), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_power_consumption', sa.Integer(), nullable=True),
    sa.Column('compatibility_status', sa.String(length=20), nullable=True),
    sa.Column('compatibility_notes', sa.Text(), nullable=True),
    sa.Column('compatibility_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('availability_status', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configurations_id'), 'configurations', ['id'], unique=False)
    op.create_index(op.f('ix_configurations_name'), 'configurations', ['name'], unique=False)
    op.create_index(op.f('ix_configurations_public_uuid'), 'configurations', ['public_uuid'], unique=True)
    op.create_table('components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('form_factor', sa.String(length=50), nullable=True),
    sa.Column('power_consumption', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['component_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_brand'), 'components', ['brand'], unique=False)
    op.create_index(op.f('ix_components_category_id'), 'components', ['category_id'], unique=False)
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_index(op.f('ix_components_name'), 'components', ['name'], unique=False)
    op.create_index(op.f('ix_components_price'), 'components', ['price'], unique=False)
    op.create_table('component_compatibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component1_id', sa.UUID(), nullable=False),
    sa.Column('component2_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['component1_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['component2_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_compatibility_component1_id'), 'component_compatibility', ['component1_id'], unique=False)
    op.create_index(op.f('ix_component_compatibility_component2_id'), 'component_compatibility', ['component2_id'], unique=False)
    op.create_index(op.f('ix_component_compatibility_id'), 'component_compatibility', ['id'], unique=False)
    op.create_table('component_stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_stock_component_id'), 'component_stock', ['component_id'], unique=False)
    op.create_index(op.f('ix_component_stock_id'), 'component_stock', ['id'], unique=False)
    op.create_table('configuration_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('configuration_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_items_component_id'), 'configuration_items', ['component_id'], unique=False)
    op.create_index(op.f('ix_configuration_items_configuration_id'), 'configuration_items', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_configuration_items_id'), 'configuration_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuration_items_id'), table_name='configuration_items')
    op.drop_index(op.f('ix_configuration_items_configuration_id'), table_name='configuration_items')
    op.drop_index(op.f('ix_configuration_items_component_id'), table_name='configuration_items')
    op.drop_table('configuration_items')
    op.drop_index(op.f('ix_component_stock_id'), table_name='component_stock')
    op.drop_index(op.f('ix_component_stock_component_id'), table_name='component_stock')
    op.drop_table('component_stock')
    op.drop_index(op.f('ix_component_compatibility_id'), table_name='component_compatibility')
    op.drop_index(op.f('ix_component_compatibility_component2_id'), table_name='component_compatibility')
    op.drop_index(op.f('ix_component_compatibility_component1_id'), table_name='component_compatibility')
    op.drop_table('component_compatibility')
    op.drop_index(op.f('ix_components_price'), table_name='components')
    op.drop_index(op.f('ix_components_name'), table_name='components')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_index(op.f('ix_components_category_id'), table_name='components')
    op.drop_index(op.f('ix_components_brand'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_configurations_public_uuid'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_name'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_id'), table_name='configurations')
    op.drop_table('configurations')
    op.drop_index(op.f('ix_component_categories_name'), table_name='component_categories')
    op.drop_index(op.f('ix_component_categories_id'), table_name='component_categories')
    op.drop_table('component_categories')
    # ### end Alembic commands ### 