"""add_configuration_accessories_table

Revision ID: 958f38a5c5d6
Revises: f14d32c55a4e
Create Date: 2025-05-27 12:44:11.378495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958f38a5c5d6'
down_revision = 'f14d32c55a4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_accessories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('configuration_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_accessories_component_id'), 'configuration_accessories', ['component_id'], unique=False)
    op.create_index(op.f('ix_configuration_accessories_configuration_id'), 'configuration_accessories', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_configuration_accessories_id'), 'configuration_accessories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuration_accessories_id'), table_name='configuration_accessories')
    op.drop_index(op.f('ix_configuration_accessories_configuration_id'), table_name='configuration_accessories')
    op.drop_index(op.f('ix_configuration_accessories_component_id'), table_name='configuration_accessories')
    op.drop_table('configuration_accessories')
    # ### end Alembic commands ### 