"""add_status_field_to_configuration

Revision ID: f14d32c55a4e
Revises: 164b31cdf665
Create Date: 2025-05-24 16:33:30.845573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14d32c55a4e'
down_revision = '164b31cdf665'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configurations', 'status')
    # ### end Alembic commands ### 